### ISSUE TITLE
Can't get unstuck

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/LimitlessBugs#11]
Well, that's not totally true, but getting stuck inside a block with the only option of relogging is kind of annoying. Essentially if I place a block where my head is, I can't break or move out of block. Little suggestion.

**Comment by dphfox** [comment]
Thanks for reporting, this will be looked into!

..but still, why would you do that 😛

**Comment by martinjonsson01** [comment]
This will be fixed in version 1.3.0 with the teleport command.
