### ISSUE TITLE
Update Log Blank, and Game Crashes

### ISSUE THREAD

**Issue by Cutout1** [StarQuestMinecraft/LimitlessBugs#12]
So I've talked about this a bit in Discord, but I still haven't gotten it to work. When I open the game, it's all white except for the title, the login, the loading bar, and the play button. The update log and background don't work, except for when I'm resizing the window they show up for a second. When I click "Login as Guest" my game just crashes. Here's a video depicting it: [https://www.youtube.com/watch?v=fN-OmOE0Wxs&feature=youtu.be](url)

**Comment by dphfox** [comment]
Thanks for reporting! Can you upload the crash log to pastebin and link it?

**Comment by Cutout1** [comment]
Well, I tried looking for the crash logs a few days ago, and I couldn't find them. Where are they?

**Comment by dphfox** [comment]
They should be in the same directory as the game executable. If they aren't there, then I can't really help further.

It seems to run fine on my Windows 10 installation, maybe there is a bug related to your installation.

**Comment by Cutout1** [comment]
I don't know, I've tried reinstalling it like 10 times by now. I just reinstalled it again and tried running it, then when it crashed and said a crash log was saved, I looked through all the files but I couldn't find it.

**Comment by Cutout1** [comment]
Found a crash log
http://pastebin.com/NJHBnUgz

**Comment by Denyol** [comment]
Can you please post your system specs.

**Comment by Cutout1** [comment]
16 GB of RAM
1 TB storage, plenty of free space
Intel i7 5700-HQ (Quad Core w/ hyperthreading at 2.7 ghz)
GTX 970M w/ 3 gb of Video RAM
64 bit windows 10

**Comment by Cutout1** [comment]
I'll try on a different system of mine later, I'll make another comment when I'm done.

**Comment by Denyol** [comment]
This seems mostly like a graphics card issue, please tell me what files are located in `C:\Users\dnlgl\AppData\LocalLow\DefaultCompany\Limitless Launcher\GameData\`, please also attempt to run the program as admin (if thats still a windows thing..)

**Comment by Cutout1** [comment]
Hmm... I thought I had tried running it as an administrator before. Apparently not. It worked when I tried running it as an admin. Thanks for the help.

**Comment by Denyol** [comment]
Everything works now?

**Comment by Cutout1** [comment]
Actually, it seems the change log still isn't working... But the game starts and works fine it seems. Jumping doesn't seem very natural, you jump high and fall slowly, but I mean it works.

**Comment by Denyol** [comment]
Has this been fixed with the latest launcher version? www.whirlwindgames.com

**Comment by martinjonsson01** [comment]
Going to bump this. What Dan said ^ @Cutout1

**Comment by martinjonsson01** [comment]
Closing this since there has been no reply and we are planning to rewrite the launcher completely soon. If you are still having problems with the latest launcher then please open a new issue.
