### ISSUE TITLE
Spawn point TP magic fizzbizz

### ISSUE THREAD

**Issue by ghost** [StarQuestMinecraft/LimitlessBugs#13]
Whenever I exit then enter an already made game I start at the spawn point not where I left off

Suggestion: keep a txt file to refer to the coordinates that the player exited with, so that they can spawn there

Also fiercedude and I are friends so try not to screw with him, I know it is fun but still

**Comment by dphfox** [comment]
Thanks for reporting! We currently don't store player information outside of inventory and hotbar contents, however we will store more player information such as location in the future. This also happens in earlier versions of Limitless.

**Comment by GingerWalnut** [comment]
This has been added for the next release.
