### ISSUE TITLE
So this fell out of the sky

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/LimitlessBugs#14]
Not entirely sure what I did. It seems to copy slices off mountains and drop them down sideways near me. This was the only time the piece was small enough not to lag crash me. More testing needed. 
On Windows 10, v2.0 
![bugreport](https://cloud.githubusercontent.com/assets/9120968/21207151/ac8dd964-c223-11e6-9ea9-74773dcc5014.PNG)

**Comment by martinjonsson01** [comment]
Looks like a terrain generation/vehicle bug? @Elttob Does this look familiar?

**Comment by dphfox** [comment]
No idea at all unfortunately, terrain is only generated into structure 0 so
this is a vehicle bug. Might want to ask Dib.

**Comment by StarQuestMinecraft** [comment]
Are you pressing "p" a lot? May be that you're spawning vehicles. Not sure
what the state of vehicles is in this version. Currently out of the country
but will check it when I return on Jan 3.

**Comment by brickworm2012** [comment]
This was the one world I was trying to use one vehicle, so not that I'm aware of. I've actually not had this issues where I was running around pressing "p" trying to crash the world. 
If you don't find the issue, it may be because this world updated from an older version after I reinstalled Limitless.  That's where I've had a lot of issues.
