### ISSUE TITLE
Bounding box bork caused by grass

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/LimitlessBugs#15]
EDIT: Once grass is broken on a block, trying to replace on or through it will leave the space uneditable until relogging. It also borks the bounding box by leaving it behind on blocks or simply not showing up. 
Windows 10, v2.0 or 1.11 or whatever the version is. 
![bugreport](https://cloud.githubusercontent.com/assets/9120968/21233572/da13beb0-c2ac-11e6-8d17-a191ef9fedf9.PNG)

**Comment by GingerWalnut** [comment]
Fixed for next version
