### ISSUE TITLE
Directly looking down/up doesn't make you move

### ISSUE THREAD

**Issue by daredevil28** [StarQuestMinecraft/LimitlessBugs#3]
When looking up or down, you are not able to move, it seems like you also walk the fastest when you look straight ahead.

**Comment by daredevil28** [comment]
Update: if you look down, you can still walk sidewards.

**Comment by dphfox** [comment]
This is due to the way the player movement is handled. We can look into modifying the system, thanks for reporting!

**Comment by GingerWalnut** [comment]
This has been fixed in the next release

**Comment by martinjonsson01** [comment]
Let's close it then.
