### ISSUE TITLE
Multiplayer Match Creation does not work.

### ISSUE THREAD

**Issue by Oriomium** [StarQuestMinecraft/LimitlessBugs#5]
When clicked upon, the "Create Internet Match" button appears to have been clicked, yet no match is created and the game concedes to doing nothing. Nothing freezes or lags, but the game virtually believes that the button was not pressed at all. This means that server hosting or any form of multiplayer beyond LAN connection is impossible.

**Comment by dphfox** [comment]
The multiplayer feature is being worked on, and we'll soon have a proper system for doing it. Thanks for reporting though!

**Comment by GingerWalnut** [comment]
Multiplayer should be back in the next update!
