### ISSUE TITLE
World generation issue

### ISSUE THREAD

**Issue by DjMcMuffin** [StarQuestMinecraft/LimitlessBugs#6]
I open the world and explore for maybe 15 seconds, then look up to see a floating mass of blocks 
http://prntscr.com/d0m7zc

**Comment by DjMcMuffin** [comment]
EDIT: this is run on Windows 10 on the x32 version of limitless

**Comment by dphfox** [comment]
Thanks for reporting. This will hopefully be fixed in the next version, we'll take the terrain into the back room and discipline it.

**Comment by martinjonsson01** [comment]
This bug has not been observed during rigorous testing of the game, so I'll close this. Please reopen if the issue appears again in 1.3.0
