### ISSUE TITLE
Text Chat Systems Lacking Exit/Enter Feature

### ISSUE THREAD

**Issue by Pairjax** [StarQuestMinecraft/LimitlessBugs#7]
I use a Mac OS with x64, and when using the text system, there is no button for exiting. I specifically pressed every button on the keyboard just to make sure it wasn't simply an odd button. However, I did not do combinations of buttons.

Text buttons that were actual symbols would go into the text box. Left clicking would select all the text, and the delete button would remove the text. Right click did not have any effect.

Tongonto said this was an issue for multiple mac users, so I believe this may be the issue.

**Comment by martinjonsson01** [comment]
This has been fixed in the latest version.
